version: '3.9'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/dev/express/Dockerfile
    env_file: ./.env  
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "1997:1997"
    depends_on:
      - mongodb
    networks:
      - mern-project_villa

  frontend:
    build:
      context: .
      dockerfile: ./docker/dev/frontend/Dockerfile
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-project_villa

  maildev:
   image: maildev/maildev:2.2.1
   restart: always
   ports:
    - "1080:1080"
    - "1025:1025"
   environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
   networks:
      - mern-project_villa


  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
         - mongodb
    ports:
        - "8081:8081"
    environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
      - mern-project_villa

  mongodb:
      image: mongo:5.0.6-focal
      restart: always
      ports:
          - "27017:27017"
      environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      volumes:
          - mongodb-data:/data/db
      networks:
        - mern-project_villa

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend  
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - mern-project_villa

networks:
  mern-project_villa:
    driver: bridge

volumes:
  mongodb-data:
  static_volume:
