version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - mern-project_villa

networks:
  mern-project_villa:
    driver: bridge
