version: '3.9'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - .:/app
    # ports:
    #   - "1997:1997"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_ROOT_USERNAME: 033136d6d2fe94034ee2
      MONGO_ROOT_PASSWORD: 46fe88eeada4fdb8ea9c9e227cc3db28f9d1df4f21666539602678afa46a3955
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb/mernproject
    networks:
      - mern-project_villa

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-project_villa

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      - mern-project_villa
    ports:
      - "8025:8025"
      - "1025:1025"

  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
         - mongodb
    ports:
        - "8081:8081"
    environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
      - mern-project_villa

  mongodb:
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
    image: mongo:5.0.6-focal
    networks:
      - mern-project_villa
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb-data:/data/db

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend  
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - mern-project_villa

networks:
  mern-project_villa:
    driver: bridge

volumes:
  mongodb-data:
  static_volume:
