version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-project_villa

  frontend:
    build:
      context: .
      dockerfile: ./docker/local/frontend/Dockerfile
    restart: on-failure
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
       - WATCHPACK_POLLING=true
       - CHOKIDAR_USEPOLLING=true
    networks:
       - mern-project_villa

  mongodb:
      image: mongo:5.0.6-focal
      restart: always
      container_name: mongo-db
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      volumes:
        - mongodb-data:/data/db
      networks:
        - mern-project_villa
        
  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
         - mongodb
    ports:
        - "8081:8081"
    environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
        - mern-project_villa
    
  mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - mern-project_villa

  nginx:
    build:  
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - mern-project_villa

networks:
  mern-project_villa:
    driver: bridge


volumes:
  mongodb-data:
  static_volume: